### ISSUE TITLE
Need language support and audio related

### ISSUE THREAD

**Issue by ImmanuelJeswyn** [Macronair/TheMillionaireGame#26]
Feature Request - Provide option to add question in other language (I tried with my native language Tamil. Its all question marks. Provide option to change music files, since the original sound tracks will bring copy right problems in social media.

**Comment by Maerciez** [comment]
The language issue is probably caused by the font that is used in the application. I'm working on a new version that allows you to change the font (and also the sound cues).

**Comment by ImmanuelJeswyn** [comment]
Thanks. Waiting...After days of searching yours is the only one practically usable.

**Comment by Macronair** [comment]
I saw this issue is still open. UTF-8 support is added in version 1.1 (useful for example when you write questions in other languages).
