### ISSUE TITLE
full screen please!!!

### ISSUE THREAD

**Issue by mathieufitzgerald** [Macronair/TheMillionaireGame#32]
Would it be possible to have full screen host, guest and audience screen?? as now we cant make them bigger thanks

**Comment by mathieufitzgerald** [comment]
i have fixed the issue myself for the host and guest screen . i forked your project and posted on my fork so have a look if you want :)

**Comment by Maerciez** [comment]
Sorry for my late response. I've had a full schedule couple of weeks. But great job!
I will dive into the fork when i'm back home.
I'm planning to continue this project to improve certain things (the tv/guest/host screens for example)

**Comment by mathieufitzgerald** [comment]
No problem! It is an amazing software so please take your time working on it, no need for rush. Would be also cool in the future to have different themes ? Like UK, US, and others where we  would have different colors, money tree etc.......
