### ISSUE TITLE
Question set import

### ISSUE THREAD

**Issue by davemachala** [Macronair/TheMillionaireGame#36]
It would be nice to be able to import all questions at once, for example from an Excel file. Of course with all attributes, such as a correct answer, description,  etc.

**Comment by Macronair** [comment]
This is a great idea and never thought of it to implement such feature. But I will say that this is something that'll be picked up at a later time. First i'm working on a version 1.1 which will fix some major (and minor) issues and errors.

But thanks for your suggestion! ;)

**Comment by Macronair** [comment]
In version 1.2, there is a feature added to import/export CSV files and make your own files.
The guide is found here: https://github.com/Macronair/TheMillionaireGame/blob/master/Guides/Exporting%20and%20Importing%20CSV%20Files.md
