### ISSUE TITLE
Problems with Win 11

### ISSUE THREAD

**Issue by NSZ010124** [Macronair/TheMillionaireGame#39]
I have a Win 11 PC and I couldn't start the program, because I get a 50 Error code Local Database Runtime Error, and I absolutely can't find the solution for this. I spent a whole month for this and still nothing. Any idea? I would be appreciate, because I've used this before (and I really liked it) my another PC which was a Win 10 operating system, and worked perfectly. Oh and 1 suggestion! The Lights Down sound needs to be change and a bonus lifelines (for example. you have 5 or 6 lifelines maybe or you choose the option: switch the question or double tip or else)

**Comment by Ep1cSpartan** [comment]
Try to re-install the SQL LocalDB (located in the application directory \SQLInstaller) I'm running it on Win11 and it runs fine.

**Comment by NSZ010124** [comment]
I've tried it, and still nothing honest. I don't know what is the problem with this Win 11, but I feel very disappointed about this MySQL Server, because I have a dbforge SQL application and it doesn't work either.

**Comment by Macronair** [comment]
I tested it for myself on a Windows 11 PC, but don't have any problems at the moment.
If your problem still persists, can you show me a screenshot of the error when you try and run the program?
Maybe I can still help you with that. Thanks!
