### ISSUE TITLE
Custom Theme and Animation

### ISSUE THREAD

**Issue by nguyennhimbth** [Macronair/TheMillionaireGame#46]
Can you make like the theme changer and making animation on the question?
https://ailatrieuphu.fandom.com/vi/wiki/B%E1%BB%99_s%C6%B0u_t%E1%BA%ADp
(some of source I found)

**Comment by Macronair** [comment]
Thanks for your suggestion. This is on my list for a while now.
The new version is almost complete (1.1) but I think that the texture customization options will be added in 1.2.

**Comment by Macronair** [comment]
Good question. But I don't know for sure. Great chance it will be next week.
Also, I uploaded a new video about the new version. There are some little bugs that needs to be fixed. But it will not take a long time:

You can find the video here: https://youtu.be/NVtr-75A5mc

**Comment by Macronair** [comment]
A couple of new themes are added to version 1.2. For the animations, I will add this to a later version/build. It is on the to-do list.
