### ISSUE TITLE
Customizable safety net

### ISSUE THREAD

**Issue by Ep1cSpartan** [Macronair/TheMillionaireGame#55]
Feature Idea: 
I was watching episodes from the British Who Want's to be a Millionaire and there contestants are able to set their own safety net in the range from 2,000 - 500,000 after reaching the question before it. Example: the contestant answered right at 8,000, they could set their safety net at 16,000. I can lookup references if necessary, if that helps

**Comment by Macronair** [comment]
Yeah I saw this as well. Only watched couple episode of the first series in 2018 when this was indeed the case. (Episodes from later series are not available to me as I'm a Dutch citizen ;)).
I noted it on my to do list for the future releases.

**Comment by Ep1cSpartan** [comment]
Let me know if I can help with any questions regarding the episodes, I'm from Germany, but I recorded quite a lot of episodes on British tv :)

**Comment by Macronair** [comment]
Free Mode is added in version 1.2 which is based on the UK format from 2018-present. Contestants can set their own 2nd safety net after question 5.
