### ISSUE TITLE
Add option to disable 'Show Correct' toggle with new questions

### ISSUE THREAD

**Issue by hazzuk** [Macronair/TheMillionaireGame#65]
Please add an option automating the following: 

- If the 'Show Correct' toggle is enabled when a new question is shown, disable the 'Show Correct' toggle.

Most often I enable the 'Show Correct' toggle just before revealing the answer. But I forget to disable it before showing the next question. Meaning I accidently see the answer when I don't want to.

**Comment by Macronair** [comment]
I had noticed it myself too recently haha.
In the next update, this option will be added. Thanks for your feedback. ;)

**Comment by Macronair** [comment]
This option is added in version 1.2
