### ISSUE TITLE
Add Question Level 'difficulty groups'

### ISSUE THREAD

**Issue by hazzuk** [Macronair/TheMillionaireGame#66]
Currently each question has to be set to a specific level (e.g. 7). This functionality allows for precise placement of questions (and this functionality should remain) but alone, it's extremely time consuming when adding new questions. One, it's hard sorting out which questions should be at which precise levels. And two, then making sure you've placed a question at all fifteen levels to provide a full game is hard to manage. 

Instead I propose the following:

**When a user adds a questions, the question is either set to a question level (as is current functionality), OR set to a question difficulty group. There are three difficulty groups, easy (levels 1-5), medium (6-10) and hard (11-15).**

- When a question is being selected from the database during the game, the game will first try to pick questions at the games current question level.  _(e,g, if the current question level is 4, it will look for questions specifically set at question level 4)._ 

- Else, the game will pick a question with a set question difficulty group matching the current question level _(e.g. if the current question level is 4, and there are no questions set to question level 4. Look for a question with a question difficulty groups set as easy)._

---

For myself, and likely many others who use this amazing software, precise placement of questions (in what is mostly a game of fun), currently requires too much time and effort to manage. This (and CSV importing) would make a huge difference to improving what right now is the hardest part of using this software, adding new questions.

**Comment by Macronair** [comment]
Very good point! Currentl;y I'm working on a feature for CSV export/import of the questions.
As for the difficulty settings, I will take the info you gave with me in the developement for the new version.

Currently I'm focusing in fixing the existing bugs and errors that are occuring. When this is solved, then this is the next step.
Btw, thanks for your feedback to the software. Really appreciate it. ;)

**Comment by Macronair** [comment]
This feature is added in 1.1 and improved/fixed some bugs in 1.2.
