### ISSUE TITLE
Cannot Set Question Difficulty to Range

### ISSUE THREAD

**Issue by glhfson** [Macronair/TheMillionaireGame#72]
Hi, your app is amazing!

However, I can't get to set my questions to specific range that I want.

There's an error box everytime I tried to do it. Can you help me?

![image](https://github.com/Macronair/TheMillionaireGame/assets/161231183/2ea094c1-bee6-4171-b399-a6c755e3282d)

**Comment by Macronair** [comment]
A new version is out where I fixed this issue. Please try 1.2 and see if it returns the same result.
